application: rnicu-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/*
  static_dir: static
  secure: always
- url: /.*
  script: rnicu.application
  secure: always
  

  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"